dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

cache:
  directories:
    - node_modules

script:
  - npm run test

jobs:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
  include:
    - stage: compile
      name: "Compilation"
      script: truffle compile


