dist: focal
sudo: required
language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm install

jobs:
  fast_finish: true
  include:
    - stage: tests
      name: "unit tests"
      script: npm run test
